# Generated by Django 6.0.6 on 2026-07-02 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=20, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='lb', max_length=20, verbose_name='Unidad de medida')),
                ('peso_unitario_lb', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso de cada unidad en libras', max_digits=8, verbose_name='Peso unitario (lb)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='Carnet de Identidad')),
                ('cuenta_banco', models.CharField(max_length=20, verbose_name='Cuenta Bancaria')),
                ('en_lista_negra', models.BooleanField(default=False, verbose_name='¿En lista negra?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('tipo_pedido', models.CharField(blank=True, choices=[('contenedor', 'Contenedor'), ('paqueteria', 'Paquetería (< 200 lb)')], max_length=15)),
                ('peso_total_lb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso total (lb)')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del cliente')),
                ('fecha_limite_recogida', models.DateField(blank=True, null=True)),
                ('dias_para_recoger', models.PositiveIntegerField(default=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='polls.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_unitario_lb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='polls.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.producto')),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Líneas de Pedido',
            },
        ),
    ]
